[profile.default]
src = "src"
out = "out"
libs = ["lib"]
remappings = [
    "@thirdweb-dev/=lib/contracts/",
    "@openzeppelin/=lib/openzeppelin-contracts/",
    "account-abstraction/=lib/account-abstraction/"
]

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
